# Generated by Django 4.1.2 on 2022-10-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='expiry',
            field=models.DateField(null=True),
        ),
    ]
