# Generated by Django 4.1.2 on 2022-10-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_job_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='option',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Internship', 'Internship')], default=False, max_length=12),
        ),
    ]
