# Generated by Django 4.1.2 on 2022-10-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_job_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='descriptions',
            field=models.TextField(null=True),
        ),
    ]
