# Generated by Django 4.1.2 on 2022-10-29 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_job_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.location'),
        ),
        migrations.AlterField(
            model_name='job',
            name='option',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Internship', 'Internship')], default='Monthly', max_length=12),
        ),
    ]
