# Generated by Django 4.1.2 on 2022-10-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_job_location_alter_job_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='option',
            field=models.CharField(choices=[('Full Tile', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship')], default='Monthly', max_length=12),
        ),
    ]
