# Generated by Django 4.1.2 on 2022-10-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0004_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
