# Generated by Django 4.1.2 on 2022-10-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_registeration_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='option',
            field=models.CharField(choices=[('W', 'Weekly'), ('M', 'Monthly'), ('I', 'Internship')], max_length=2),
        ),
    ]
