# Generated by Django 4.1.2 on 2022-10-29 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_alter_registeration_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeration',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
