# Generated by Django 4.1.2 on 2022-10-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_rename_fist_name_registeration_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='option',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Internship', 'Internship')], default='Monthly', max_length=22),
        ),
    ]
